background_opacity: 0.9

draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '0x44475a'
      background: '0x50fa7b'
    focused_match:
      foreground: '0x44475a'
      background: '0xffb86c'
    bar:
      background: '0x282a36'
      foreground: '0xf8f8f2'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '0x44475a'
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'
  bright:
    black:   '0x4d4d4d'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'

env:
  TERM: xterm-256color
font:
  bold:
    family: Source Code Pro
    style: Bold
  bold_italic:
    family: Mononoki Nerd Font
    style: Bold Italic
  italic:
    family: Source Code Pro
    style: Italic
  normal:
    family: Mononoki Nerd Font
    style: Regular
  offset:
    x: 0
    y: 1
  size: 8.0
key_bindings:
- action: Paste
  key: V
  mods: Control|Shift
- action: Copy
  key: C
  mods: Control|Shift
- action: PasteSelection
  key: Insert
  mods: Shift
- action: ResetFontSize
  key: Key0
  mods: Control
- action: IncreaseFontSize
  key: Equals
  mods: Control
- action: IncreaseFontSize
  key: Plus
  mods: Control
- action: DecreaseFontSize
  key: Minus
  mods: Control
- action: DecreaseFontSize
  key: Minus
  mods: Control
- action: ToggleFullscreen
  key: F11
  mods: None
- action: Paste
  key: Paste
  mods: None
- action: Copy
  key: Copy
  mods: None
- action: ClearLogNotice
  key: L
  mods: Control
- chars: "\f"
  key: L
  mods: Control
- action: ScrollPageUp
  key: PageUp
  mode: ~Alt
  mods: None
- action: ScrollPageDown
  key: PageDown
  mode: ~Alt
  mods: None
- action: ScrollToTop
  key: Home
  mode: ~Alt
  mods: Shift
- action: ScrollToBottom
  key: End
  mode: ~Alt
  mods: Shift
scrolling:
  history: 5000
window:
  class:
    general: Alacritty
    instance: Alacritty
  dynamic_padding: true
  padding:
    x: 0
    y: 0
  title: Alacritty
