#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#96CDFB"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Emacs state=tiled
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
picom &
dunst &
killall polybar
polybar bar &
nitrogen --set-scaled ~/Downloads/wallpaper.png &
xautolock -locker "i3lock -c 181825" -time 5 &
